#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
gnb:
  resources:
    limits:
      cpu: null
      memory: null
    requests:
      cpu: 250m
      memory: 256Mi
  configuration: |-
    nci: '0x000000010'  # NR Cell Identity (36-bit)
    idLength: 32        # NR gNB ID length in bits [22...32]
    tac: 1     # Tracking Area Code
    # List of supported S-NSSAIs by this gNB
    # Indicates whether or not SCTP stream number errors should be ignored.
    ignoreStreamIds: true

    mcc: '901'
    mnc: '70'
    slices:
      - sst: 1

ue:
  resources:
    limits:
      cpu: null
      memory: null
    requests:
      cpu: 120m
      memory: 128Mi
  command: "./nr-ue -c ../config/ue-config.yaml -n 500"
  configuration: |-
    supi: 'imsi-901700000000001'
    mcc: '901'
    mnc: '70'
    key: '465B5CE8B199B49FAA5F0A2EE238A6BC'
    op: 'E8ED289DEBA952E4283B54E88E6183CA'
    opType: 'OPC'
    amf: '8000'
    imei: '356938035643803'
    imeiSv: '4370816125816151'
    # UAC Access Identities Configuration
    uacAic:
      mps: false
      mcs: false
    # UAC Access Control Class
    uacAcc:
      normalClass: 0
      class11: false
      class12: false
      class13: false
      class14: false
      class15: false
    sessions:
      - type: 'IPv4'
        apn: 'internet'
        slice:
          sst: 1
    # Configured NSSAI for this UE by HPLMN
    configured-nssai:
      - sst: 1
    # Default Configured NSSAI for this UE
    default-nssai:
      - sst: 1
        sd: 1
    # Supported encryption and integrity algorithms by this UE
    integrity:
      IA1: true
      IA2: true
      IA3: true
    ciphering:
      EA1: true
      EA2: true
      EA3: true
      # Integrity protection maximum data rate for user plane
    integrityMaxRate:
      uplink: 'full'
      downlink: 'full'
