N3IWFInformation:
  GlobalN3IWFID:
    PLMNID:
      MCC: 208
      MNC: 93
    N3IWFID: 135
  Name:
    free5GC_N3IWF
  SupportedTAList:
    - TAC: 000001
      BroadcastPLMNList:
        - PLMNID:
            MCC: 208
            MNC: 93
          TAISliceSupportList:
            - SNSSAI:
                SST: 1
                SD: 010203
            - SNSSAI:
                SST: 1
                SD: 112233

# IPSec virtual interface
IPSecInterfaceAddress: 10.0.0.1

# IPSec virtual interface mark
IPSecInterfaceMark: 5

# NAS TCP Listen Port
NASTCPPort: 20000

# N3IWF FQDN
FQDN: n3iwf.free5gc.org

# Security
# Private Key File Path
PrivateKey: ../cert/n3iwf.key
# Certificate Authority (CA)
CertificateAuthority: ../cert/n3iwf.pem
# Certificate
Certificate: ../cert/n3iwf.pem

# IP address that will be allocated to UE in IPSec tunnel
UEIPAddressRange: 10.0.0.0/24
