#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- if .Values.nrf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nrf.configmap.name }}
  labels:
    app: {{ .Values.global.projectName }}
data:
  nrfcfg.yaml: |
    info:
      version: 1.0.0
      description: NRF initial local configuration
    
    configuration:
      MongoDBName: free5gc
      MongoDBUrl: mongodb://{{ .Values.mongodb.service.name }}:{{ .Values.mongodb.service.port }}
      sbi:
        scheme: {{ .Values.global.sbi.scheme }}
        registerIPv4: {{ .Values.nrf.service.name }} # IP used to serve NFs or register to another NRF
        bindingIPv4: 0.0.0.0  # IP used to bind the service
        port: {{ .Values.nrf.port }}
      DefaultPlmnId:
        mcc: 208
        mnc: 93
      serviceNameList:
        - nnrf-nfm
        - nnrf-disc
    
    logger:
      NRF:
        debugLevel: info
        ReportCaller: false
      PathUtil:
        debugLevel: info
        ReportCaller: false
      OpenApi:
        debugLevel: info
        ReportCaller: false
      MongoDBLibrary:
        debugLevel: info
        ReportCaller: false
{{- end }}

