#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
global:
  userPlaneArchitecture: ulcl  # possible values are "single" and "ulcl"

smf:
  configuration:
    configuration:
      userplane_information:
        up_nodes:
          gNB1:
            type: AN
            an_ip: 10.100.50.236
          BranchingUPF:
            type: UPF
            node_id: 10.100.50.241 # PFCP address
            sNssaiUpfInfos:
              - sNssai:
                  sst: 1
                  sd: 010203
                dnnUpfInfoList:
                  - dnn: internet
              - sNssai:
                  sst: 1
                  sd: 112233
                dnnUpfInfoList:
                  - dnn: internet
            interfaces:
              - interfaceType: N3
                endpoints:
                  - 10.100.50.233
                networkInstance: internet
              - interfaceType: N9
                endpoints:
                  - 10.100.50.225
                networkInstance: internet
          AnchorUPF1:
            type: UPF
            node_id: 10.100.50.242 # PFCP address
            sNssaiUpfInfos:
              - sNssai:
                  sst: 1
                  sd: 010203
                dnnUpfInfoList:
                  - dnn: internet
            interfaces:
              - interfaceType: N9
                endpoints:
                  - 10.100.50.226 # UPF1 N9 address
                networkInstance: internet
          AnchorUPF2:
            type: UPF
            node_id: 10.100.50.243 # PFCP address
            sNssaiUpfInfos:
              - sNssai:
                  sst: 1
                  sd: 010203
                dnnUpfInfoList:
                  - dnn: internet
            interfaces:
              - interfaceType: N9
                endpoints:
                  - 10.100.50.227 # UPF2 N9 address
                networkInstance: internet
        links:
          - A: gNB1
            B: BranchingUPF
          - A: BranchingUPF
            B: AnchorUPF1
          - A: BranchingUPF
            B: AnchorUPF2






