#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- if and .Values.gnb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gnb.service.name }}
  labels:
    app: {{ .Values.projectName }}
    component: {{ .Values.gnb.name }}
spec:
  type: {{ .Values.gnb.service.type }}
  ports:
    - name: gnb-ue
      port: {{ .Values.gnb.service.port }}
      protocol: {{ .Values.gnb.service.protocol }}
  selector:
    app: {{ .Values.projectName }}
    component: {{ .Values.gnb.name }}
{{- end }}

