#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- if .Values.global.n2network.enabled }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Values.global.n2network.name }}
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": {{ .Values.global.n2network.masterIf | quote }},
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "subnet": "{{ .Values.global.n2network.subnetIP }}/{{ .Values.global.n2network.cidr }}",
        "exclude": [ "{{ .Values.global.n2network.excludeIP }}/{{ .Values.global.n2network.cidr }}" ],
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "{{ .Values.global.n2network.gatewayIP }}"
      }
    }'
{{- end }}
